### PR TITLE
Order limit - implements #1

### PR DESCRIPTION
**Pull request by Iiridayn**
Changefeeds with `orderBy` require `limit`, and with `limit` require `orderBy`, see https://rethinkdb.com/docs/changefeeds/javascript/ ("`orderBy` requires `limit`; neither command works by itself."). Since we required a search which returned only the most recent of something, we have implemented it.

### CODE REVIEW

**Comment by yasserf** [comment]
@WolframHempel can you take a look at this when you have some time?

**Comment by layanto** [comment]
@Iiridayn, https://www.rethinkdb.com/api/javascript/order_by/ doesn't say that orderBy must be used together with limit. But I tried using just orderBy without limit (removing the XOR parseInput check first), I found that while the query ran, it returned data with incorrect order. Adding a limit immediately return the correct ordering. Not sure why.
Also orderBy can be used without creating index on the field to be ordered by but will need a different query. Not sure if you want to be able to handle either with or without index.

EDIT - never mind. Saw that this limitation is to do with changefeed.

**Comment by layanto** [comment]
Tried this pull request and can confirm the new options (order, desc and limit) work.

**Comment by yasserf** [comment]
@layanto Thank you for the QA! 
@Iiridayn Thank you for the PR!

I'll merge this in now, and include in the 2.0 release. Would that be okay or would u rather have it as a seperate release prior to 2.0 compatability?

**Comment by Iiridayn** [comment]
No worries, thanks for the release :). We've been running a local rewrite (different style, using functional programming/closures instead of OOP) while we've been waiting. I've just switched us back to the official release :).

**Comment by layanto** [comment]
@Iiridayn actually maybe I did a bad QA. With desc: true, the initial value is ordered correctly, but on subsequent updates to rethinkDb, the new entries are added to the bottom of list instead of top.
For example with limit 5, initial value of [ 50, 40, 30, 20, 10 ]
Adding two new entries of 60 and 70, expected list is [70, 60, 50, 40, 30] but actual list returned is [ 50, 40, 30, 60, 70 ]

**Comment by Iiridayn** [comment]
Indeed - the reason `orderBy` is supported is to support a meaningful `limit` - your results of `[50, 40, 30, 60, 70]` are correct, as far as actual data, which is and was my only concern. For sorting of client side returned arrays, whether the full set or some limited subset (which must first be ordered for the limit to return a meaningful subset) - in either case, that is - I perform sorting on the client side.

The intention of this code was never to order results - merely to limit the number of results returned to a meaningful subset. If you would like ordered results, I would encourage sorting them on the client.

**Comment by layanto** [comment]
Unless the orderBy happens to be the id field, I can't simply sort the returned array. To sort client side, you will need to retrieve all the records whose IDs are in the list, then re sort the records based on a particular field. Wasn't the behaviour I was expected but I understand that your concern is only to limit the list.

**Comment by Iiridayn** [comment]
Yep, that's what we're doing, though we're also wrapping the records in Knockout `ViewModels` in a Knockout `ObservableArray` which we sort with a `ComputedObservable` or something. If you're concerned about pagination (sort + limit + offset) - I couldn't think of a decent way to implement offset off hand, and our larger data paginated is only around 1000 records so we just grab the whole thing and sort it client side.

If you aren't paginating (including infiniscroll, etc), chances are you're displaying the lot of them, in which case you'd have to get the records to display them anyway.

For more complex queries (`HAVING`, `GROUP BY`, `ORDER BY COUNT(x)` etc) we've taken to "stored proceedure"-like listeners where we build the result we need out of a simpler live query, some of which _do_ return IDs in sorted order.

If you have a specific usecase other than pagination (which needs offset as well), it might be worth opening a new request to add that feature with the usecase detailed. If I can see us needing it too I can probably put some development time into it. Otherwise, you can always make a pull request and the deepstream team should get right on it :).

**Comment by layanto** [comment]
Maybe a dumb suggestion and may not be possible with deepstream's list. What about returning in the list both the id and the field being sorted on. Then even though the list is still out of order, can sort client side without having to get the records. So will work for pagination too.
Example list sorted by username returning [{id01, field01}, {id02, field02}...] where fieldXX contains username.

**Comment by mclark-newvistas** [comment]
Deepstream lists only accept a single string as an id; while it is possible for the search provider to grab the record information and provide a sorted list, that would be a separate ticket. Up to this point everything we've needed have either been too complex (4 most recent x sorted by a complex condition, find as you type sorted by a sequence of 4 fields), unordered (dots on a graph - doesn't matter which order they arrive), or immediately and fully displayed and so fine to order on the client side (proper ranges on displayed data, clumping by date in a pseudo-pagination).

Again, if you _do need_ this kind of feature I encourage you to open a ticket and submit a pull request. We might or might not eventually need it here; if we end up needing it we will build it then.

**Pull request merged**
